//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENTES
    {
        public int ideevento { get; set; }
        public int idusuario { get; set; }
        public Nullable<byte> inscritosqtty { get; set; }
        public Nullable<byte> asistentesqtty { get; set; }
        public Nullable<byte> valoracion { get; set; }
        public string comentarios { get; set; }
        public Nullable<byte> ctrlvaloracion { get; set; }
    
        public virtual EVENTOS EVENTOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
