//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOSINTERES
    {
        public int id { get; set; }
        public Nullable<byte> estado { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string cp { get; set; }
        public Nullable<byte> idprovincia { get; set; }
        public Nullable<byte> idccaa { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string contacto { get; set; }
        public Nullable<byte> ctrlglobal { get; set; }
        public Nullable<int> iddelegacion { get; set; }
        public Nullable<int> iddsktuser { get; set; }
    
        public virtual CCAA CCAA { get; set; }
        public virtual DELEGACIONES DELEGACIONES { get; set; }
        public virtual DSKTUSERS DSKTUSERS { get; set; }
        public virtual PROVINCIAS PROVINCIAS { get; set; }
    }
}
