//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOS
    {
        public int id { get; set; }
        public string ciddocumento { get; set; }
        public Nullable<byte> estado { get; set; }
        public Nullable<int> idevento { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> iddsktuser { get; set; }
    
        public virtual DSKTUSERS DSKTUSERS { get; set; }
        public virtual EVENTOS EVENTOS { get; set; }
    }
}
