//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTOS()
        {
            this.ASISTENTES = new HashSet<ASISTENTES>();
            this.DOCUMENTOS = new HashSet<DOCUMENTOS>();
        }
    
        public int id { get; set; }
        public string cidevento { get; set; }
        public Nullable<byte> estado { get; set; }
        public string titulo { get; set; }
        public string intro { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.TimeSpan> horainicio { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public Nullable<System.TimeSpan> horafin { get; set; }
        public byte[] imagen { get; set; }
        public string notasevento { get; set; }
        public string notastransporte { get; set; }
        public Nullable<byte> idccaa { get; set; }
        public Nullable<byte> idprovincia { get; set; }
        public string ciudad { get; set; }
        public string coordgps { get; set; }
        public Nullable<byte> ctrlglobal { get; set; }
        public Nullable<int> iddelegacion { get; set; }
        public Nullable<int> iddsktuser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASISTENTES> ASISTENTES { get; set; }
        public virtual CCAA CCAA { get; set; }
        public virtual DELEGACIONES DELEGACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTOS> DOCUMENTOS { get; set; }
        public virtual DSKTUSERS DSKTUSERS { get; set; }
        public virtual PROVINCIAS PROVINCIAS { get; set; }
    }
}
