//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EEVAPPEntities : DbContext
    {
        public EEVAPPEntities()
            : base("name=EEVAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASISTENTES> ASISTENTES { get; set; }
        public virtual DbSet<CCAA> CCAA { get; set; }
        public virtual DbSet<DATOSINTERES> DATOSINTERES { get; set; }
        public virtual DbSet<DELEGACIONES> DELEGACIONES { get; set; }
        public virtual DbSet<DOCUMENTOS> DOCUMENTOS { get; set; }
        public virtual DbSet<DSKTUSERS> DSKTUSERS { get; set; }
        public virtual DbSet<EVENTOS> EVENTOS { get; set; }
        public virtual DbSet<IDIOMAS> IDIOMAS { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
